//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Inspire.Server.Display.DataContracts
{
	/// <summary>
	/// Data Contract Class - DisplayGroup
	/// </summary>
	[WcfSerialization::DataContract(Namespace = "http://schemas.inspiredisplays.com/DataContract.Model/", Name = "DisplayGroup")]
	public partial class DisplayGroup 
	{
	    [WcfSerialization::DataMember(Name = "GUID", IsRequired = false, Order = 0)]
	    public string GUID { get; set; }

	    [WcfSerialization::DataMember(Name = "GroupName", IsRequired = false, Order = 1)]
	    public string GroupName { get; set; }

	    [WcfSerialization::DataMember(Name = "GroupDescription", IsRequired = false, Order = 2)]
	    public string GroupDescription { get; set; }

	    [WcfSerialization::DataMember(Name = "PropertyID", IsRequired = false, Order = 3)]
	    public string PropertyID { get; set; }
	}
}

