//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Inspire.Server.Display.DataContracts
{
	/// <summary>
	/// Data Contract Class - DisplayProperties
	/// </summary>
	[WcfSerialization::CollectionDataContract(Namespace = "http://schemas.inspiredisplays.com/DataContract.Model/", ItemName = "DisplayProperties")]
	public partial class DisplayProperties : System.Collections.Generic.List<DisplayProperty>
	{
	}
}

