//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Net.Security;
using WCF = global::System.ServiceModel;
using Inspire.Server.Common.FaultContracts;
using Inspire.Server.Images.MessageContracts;

namespace Inspire.Server.Images.ServiceContracts
{
	/// <summary>
	/// Service Contract Class - DirectionServiceContract
	/// </summary>
	[WCF::ServiceContract(Namespace = "http://schemas.inspiredisplays.com", Name = "ImageServiceContract", SessionMode = WCF::SessionMode.Allowed, ProtectionLevel = ProtectionLevel.None )]
	public partial interface IImageServiceContract 
	{
		[WCF::FaultContract(typeof(GeneralFaultContract))]
		[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "http://schemas.inspiredisplays.com/DirectionServiceContract/GetImages", ProtectionLevel = ProtectionLevel.None)]
		GetImagesResponseMessage GetImages(GetImagesRequestMessage request);

        [WCF::FaultContract(typeof(GeneralFaultContract))]
        [WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "http://schemas.inspiredisplays.com/DirectionServiceContract/AddImage", ProtectionLevel = ProtectionLevel.None)]
        AddImageResponseMessage AddImage(AddImageRequestMessage request);

        [WCF::FaultContract(typeof(GeneralFaultContract))]
        [WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "http://schemas.inspiredisplays.com/DirectionServiceContract/DeleteImage", ProtectionLevel = ProtectionLevel.None)]
        DeleteImageResponseMessage DeleteImage(DeleteImageRequestMessage request);

        
	}
}

