//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Inspire.Server.Registration
{
	/// <summary>
    /// Service Contract Class - RegistrationRequestMessage
	/// </summary>
	[WCF::MessageContract(IsWrapped = false)] 
	public partial class RegistrationRequestMessage
	{
	    [WCF::MessageBodyMember(Name = "FirstName")]
        public string FirstName { get; set; }

        [WCF::MessageBodyMember(Name = "LastName")]
        public string LastName { get; set; }

        [WCF::MessageBodyMember(Name = "CompanyName")]
        public string CompanyName { get; set; }

        [WCF::MessageBodyMember(Name = "Address1")]
        public string Address1 { get; set; }

        [WCF::MessageBodyMember(Name = "Address2")]
        public string Address2 { get; set; }

        [WCF::MessageBodyMember(Name = "City")]
        public string City { get; set; }

        [WCF::MessageBodyMember(Name = "State")]
        public string State { get; set; }

        [WCF::MessageBodyMember(Name = "Zip")]
        public string Zip { get; set; }

        [WCF::MessageBodyMember(Name = "Phone")]
        public string Phone { get; set; }

        [WCF::MessageBodyMember(Name = "Email")]
        public string Email { get; set; }

	    [WCF::MessageBodyMember(Name = "RegKey")]
	    public Guid RegKey { get; set; }
	}
}

