//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Inspire.Server.Common.DataContracts
{
    /// <summary>
    /// Data Contract Class - Button 
    /// </summary>
    [WcfSerialization::DataContract(Namespace = "http://schemas.inspiredisplays.com", Name = "Button")]
    public partial class Button
    {
        [WcfSerialization::DataMember(Name = "GUID", IsRequired = false, Order = 0)]
        public string GUID { get; set; }

        [WcfSerialization::DataMember(Name = "SlideID", IsRequired = false, Order = 1)]
        public string SlideID { get; set; }

        [WcfSerialization::DataMember(Name = "ButtonName", IsRequired = false, Order = 2)]
        public string ButtonName { get; set; }
              
        [WcfSerialization::DataMember(Name = "ScheduledSlideID", IsRequired = false, Order = 3)]
        public string ScheduledSlidSlideID { get; set; }

        [WcfSerialization::DataMember(Name = "SlideGuidToNavigateTo", IsRequired = false, Order = 4)]
        public string SlideGuidToNavigateTo { get; set; }
        
    }
}

