//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Inspire.Server.Common.DataContracts
{
    /// <summary>
    /// Data Contract Class - Buttons
    /// </summary>
    [WcfSerialization::CollectionDataContract(Namespace = "http://schemas.inspiredisplays.com", ItemName = "Buttons")]
    public partial class Buttons : System.Collections.Generic.List<Button>
    {
    }
}

