//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Inspire.Settings.DataContracts
{
	/// <summary>
    /// Data Contract Class - Setting
	/// </summary>
	[WcfSerialization::DataContract(Namespace = "http://schemas.inspiredisplays.com", Name = "Setting")]
	public partial class Setting 
	{
	    [WcfSerialization::DataMember(Name = "Key", IsRequired = false, Order = 0)]
        public string Key { get; set; }

        [WcfSerialization::DataMember(Name = "Value", IsRequired = false, Order = 1)]
	    public string Value { get; set; }

	  
	}
}

