//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Inspire.Settings.DataContracts
{
	/// <summary>
	/// Data Contract Class - Users
	/// </summary>
	[WcfSerialization::CollectionDataContract(Namespace = "http://schemas.inspiredisplays.com", ItemName = "Settings")]
	public partial class Settings : System.Collections.Generic.List<Setting>
	{
	}
}

