//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Inspire.Server.Groups.DataContracts;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Inspire.Server.Groups.DataContracts
{
    /// <summary>
    /// Data Contract Class - GroupAliases
    /// </summary>
    [WcfSerialization::CollectionDataContract(Namespace = "http://schemas.inspiredisplays.com", ItemName = "GroupAliases")]
    public class GroupAliases : System.Collections.Generic.List<GroupAlias>
    {
    }
}