//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ServiceModel.Activation;
using Inspire.Server.DisplayAdmin.BusinessLogic;
using Inspire.Server.DisplayAdmin.MessageContracts;
using WCF = global::System.ServiceModel;

namespace Inspire.Server.DisplayAdmin.ServiceImplementation
{
    /// <summary>
    /// Service Class - DisplayAdminService
    /// </summary>
    [AspNetCompatibilityRequirements(RequirementsMode = AspNetCompatibilityRequirementsMode.Allowed)]
	[WCF::ServiceBehavior(Name = "DisplayAdminService",
        Namespace = "http://ServiceContract.InspireDisplays.com",
        InstanceContextMode = WCF::InstanceContextMode.PerSession,
        ConcurrencyMode = WCF::ConcurrencyMode.Single)]



  
    public class DisplayAdminService : Inspire.Server.DisplayAdmin.ServiceContracts.IDisplayAdminServiceContract
    {
        public void UpdateDisplays(UpdateDisplaysRequest request)
        {
            ResourceAccess.UpdateDisplays();
        }

        // public void TriggerEmergency(UpdateDisplaysRequest request)
        //{
        //    //ResourceAccess.UpdateDisplays();
        //}

         //public void CheckAndUpdateDisplays(CheckAndUpdateDisplaysRequest request)
         //{
         //    //ResourceAccess.CheckAndUpdateDisplays();
         //}
         //public void PingDisplays(PingDisplaysRequest request)
         //{
         //    ResourceAccess.PingDisplays();
         //}


    }


}

