//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Net.Security;
using WCF = global::System.ServiceModel;

namespace Inspire.Server.DisplayAdmin.ServiceContracts
{
	/// <summary>
    /// Service Contract Class - DisplayAdminServiceContract 
	/// </summary>
	[WCF::ServiceContract(Namespace = "http://ServiceContract.InspireDisplays.com", Name = "DisplayAdminServiceContract", SessionMode = WCF::SessionMode.Allowed, ProtectionLevel = ProtectionLevel.None )]
	public partial interface IDisplayAdminServiceContract 
	{
        //[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = true, AsyncPattern = false, Action = "http://ServiceContract.InspireDisplays.com/DisplayAdminContract/CheckAndUpdateDisplaysRequest", ProtectionLevel = ProtectionLevel.None)]
        //void CheckAndUpdateDisplays(Inspire.Server.DisplayAdmin.MessageContracts.CheckAndUpdateDisplaysRequest request);

        [WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = true, AsyncPattern = false, Action = "http://ServiceContract.InspireDisplays.com/DisplayAdminServiceContract/UpdateDisplaysRequest", ProtectionLevel = ProtectionLevel.None)]
        void UpdateDisplays(Inspire.Server.DisplayAdmin.MessageContracts.UpdateDisplaysRequest request);
        
        //[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = true, AsyncPattern = false, Action = "http://ServiceContract.InspireDisplays.com/DisplayAdminServiceContract/PingDisplays", ProtectionLevel = ProtectionLevel.None)]
        //void PingDisplays(Inspire.Server.DisplayAdmin.MessageContracts.PingDisplaysRequest request);



	}
}

