//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Net.Security;
using WCF = global::System.ServiceModel;
using Inspire.Server.Common.FaultContracts;
using Inspire.Server.Direction.MessageContracts;

namespace Inspire.Server.Direction.ServiceContracts
{
	/// <summary>
	/// Service Contract Class - DirectionServiceContract
	/// </summary>
	[WCF::ServiceContract(Namespace = "http://schemas.inspiredisplays.com", Name = "DirectionServiceContract", SessionMode = WCF::SessionMode.Allowed, ProtectionLevel = ProtectionLevel.None )]
	public partial interface IDirectionServiceContract 
	{
		[WCF::FaultContract(typeof(GeneralFaultContract))]
        [WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "http://schemas.inspiredisplays.com/DirectionServiceContract/GetDirections", ProtectionLevel = ProtectionLevel.None)]
        GetDirectionsResponseMessage GetDirections(GetDirectionsRequestMessage request);

        [WCF::FaultContract(typeof(GeneralFaultContract))]
        [WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "http://schemas.inspiredisplays.com/DirectionServiceContract/AddDirection", ProtectionLevel = ProtectionLevel.None)]
        AddDirectionResponseMessage AddDirection(AddDirectionRequestMessage request);

        [WCF::FaultContract(typeof(GeneralFaultContract))]
        [WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "http://schemas.inspiredisplays.com/DirectionServiceContract/DeleteDirection", ProtectionLevel = ProtectionLevel.None)]
        DeleteDirectionResponseMessage DeleteDirection(DeleteDirectionRequestMessage request);

	}
}

