//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Inspire.Server.ScheduledSlideManager.MessageContracts
{
	/// <summary>
	/// Service Contract Class - GetScheduledSlidesResponseMessage
	/// </summary>
	[WCF::MessageContract(IsWrapped = false)] 
	public partial class GetScheduledSlidesResponseMessage
	{
	    [WCF::MessageBodyMember(Name = "Schedules")]
	    public Inspire.Server.ScheduledSlideManager.DataContracts.ScheduledSlides Schedules { get; set; }
	}
}

