//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;
using Inspire.Server.Direction.DataContracts;

namespace Inspire.Server.Direction.MessageContracts
{
	/// <summary>
	/// Service Contract Class - GetDirectionsResponseMessage
	/// </summary>
	[WCF::MessageContract(IsWrapped = false)] 
	public partial class GetDirectionsResponseMessage
	{
	    [WCF::MessageBodyMember(Name = "Directions")]
	    public Directions Directions { get; set; }
	}
}

