//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Inspire.Server.Display.MessageContracts
{
	/// <summary>
	/// Service Contract Class - GetAllDisplaysResponseMessage
	/// </summary>
	[WCF::MessageContract(IsWrapped = false)] 
	public partial class GetDisplaysResponseMessage
	{
	    [WCF::MessageBodyMember(Namespace = "http://schemas.inspiredispays.com", Name = "Displays")]
	    public DataContracts.Displays Displays { get; set; }
	}
}

