//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Net.Security;
using WCF = global::System.ServiceModel;
using Inspire.Settings.MessageContracts;


namespace Inspire.Settings.ServiceContracts
{
	/// <summary>
	/// Service Contract Class - UserServiceContract
	/// </summary>
    [WCF::ServiceContract(Namespace = "http://schemas.inspiredisplays.com", Name = "SettingServiceContract", SessionMode = WCF::SessionMode.Allowed, ProtectionLevel = ProtectionLevel.None)]
    public partial interface ISettingServiceContract 
	{
        //Inspire.Settings.ServiceContracts.ISettingServiceContract
[WCF::FaultContract(typeof(Inspire.Server.Common.FaultContracts.GeneralFaultContract))]
        [WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "http://schemas.inspiredisplays.com/UserServiceContract/GetSetting", ProtectionLevel = ProtectionLevel.None)]
        GetSettingsResponseMessage GetSetting(GetSettingsRequestMessage request);

[WCF::FaultContract(typeof(Inspire.Server.Common.FaultContracts.GeneralFaultContract))]
        [WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "http://schemas.inspiredisplays.com/UserServiceContract/AddSetting", ProtectionLevel = ProtectionLevel.None)]
        AddSettingResponseMessage AddSetting(AddSettingRequestMessage request);

[WCF::FaultContract(typeof(Inspire.Server.Common.FaultContracts.GeneralFaultContract))]
        [WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "http://schemas.inspiredisplays.com/UserServiceContract/DeleteSetting", ProtectionLevel = ProtectionLevel.None)]
        DeleteSettingResponseMessage DeleteSetting(DeleteSettingRequestMessage request);


	}
}

