//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Inspire.Server.Rooms.DataContracts;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Inspire.Server.Rooms.DataContracts
{
    /// <summary>
    /// Data Contract Class - Rooms
    /// </summary>
    [WcfSerialization::CollectionDataContract(Namespace = "http://schemas.inspiredisplays.com", ItemName = "Rooms")]
    public partial class Rooms : System.Collections.Generic.List<Room>
    {
    }
}