//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Inspire.Server.Images.MessageContracts
{
	/// <summary>
	/// Service Contract Class - AddImageResponseMessage
	/// </summary>
	[WCF::MessageContract(IsWrapped = false)] 
	public partial class AddImageResponseMessage
	{
	    [WCF::MessageBodyMember(Name = "WebPath")]
	    public string WebPath { get; set; }
	}
}

