//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Inspire.Server.SlideManager.DataContracts
{
	/// <summary>
	/// Data Contract Class - Slide
	/// </summary>
	[WcfSerialization::DataContract(Namespace = "http://schemas.inspiredisplays.com", Name = "Slide")]
	public partial class Slide 
	{
	    [WcfSerialization::DataMember(Name = "GUID", IsRequired = false, Order = 0)]
	    public string GUID { get; set; }

	    [WcfSerialization::DataMember(Name = "Name", IsRequired = false, Order = 1)]
	    public string Name { get; set; }

        [WcfSerialization::DataMember(Name = "Description", IsRequired = false, Order = 2)]
        public string Description { get; set; }

	    [WcfSerialization::DataMember(Name = "VResolution", IsRequired = false, Order = 3)]
	    public double VResolution { get; set; }

        [WcfSerialization::DataMember(Name = "HResolution", IsRequired = false, Order = 4)]
        public double HResolution { get; set; }
        
	    [WcfSerialization::DataMember(Name = "Thumbnail", IsRequired = false, Order = 5)]
	    public byte[] Thumbnail { get; set; }

        [WcfSerialization::DataMember(Name = "ModifiedBy", IsRequired = false, Order = 6)]
        public string ModifiedBy { get; set; }

        [WcfSerialization::DataMember(Name = "LastModifiedDate", IsRequired = false, Order = 7)]
        public DateTime? LastModifiedDate { get; set; }

        //[WcfSerialization::DataMember(Name = "TouchScreenButtons", IsRequired = false, Order = 8)]
        //public TouchScreenButtons TouchScreenButtons { get; set; }
        
        [WcfSerialization::DataMember(Name = "SlideRules", IsRequired = false, Order = 9)]
        public SlideRules Rules { get; set; }

        [WcfSerialization::DataMember(Name = "SlideTags", IsRequired = false, Order = 10)]
        public SlideTags Tags { get; set; }

        [WcfSerialization::DataMember(Name = "DefaultDuration", IsRequired = false, Order = 11)]
        public DateTime? DefaultDuration { get; set; }
	}


}

