//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Inspire.Server.SlideManager.DataContracts
{
	/// <summary>
	/// Data Contract Class - Rules
	/// </summary>
	[WcfSerialization::CollectionDataContract(Namespace = "http://schemas.inspiredisplays.com", ItemName = "SlideTags")]
	public partial class SlideTags : System.Collections.Generic.List<SlideTag>
	{
	}
}

