msbuild "C:\CODE\trunk\InspireServer\Server\_RebuildAll\RebuildAll.sln" /t:Rebuild /p:Configuration=Release /t:Clean
pause
Copy "C:\CODE\trunk\InspireServer\Server\Inspire.ServiceHost\bin\Release\Inspire.Server.ServiceHost.exe" C:\CODE\installers\Built_Assemblies\PreObf\Server\Core\Endpoint\Inspire.Server.ServiceHost.exe"
Copy "C:\CODE\trunk\InspireServer\Server\Inspire.ServiceHost\bin\Release\Inspire.Server.Common.dll" C:\CODE\installers\Built_Assemblies\PreObf\Server\Core\Endpoint\Inspire.Server.Common.dll"
Copy "C:\CODE\trunk\InspireServer\Server\Inspire.ServiceHost\bin\Release\Inspire.Server.Display.dll" C:\CODE\installers\Built_Assemblies\PreObf\Server\Core\Endpoint\Inspire.Server.Display.dll"
Copy "C:\CODE\trunk\InspireServer\Server\Inspire.ServiceHost\bin\Release\Inspire.Server.DisplayAdmin.dll" "C:\CODE\installers\Built_Assemblies\PreObf\Server\Core\Endpoint\Inspire.Server.DisplayAdmin.dll"
Copy "C:\CODE\trunk\InspireServer\Server\Inspire.ServiceHost\bin\Release\Inspire.Server.ScheduledSlideManager.dll" "C:\CODE\installers\Built_Assemblies\PreObf\Server\Core\Endpoint\Inspire.Server.ScheduledSlideManager.dll"
Copy "C:\CODE\trunk\InspireServer\Server\Inspire.ServiceHost\bin\Release\Inspire.Server.ScheduleManager.dll" "C:\CODE\installers\Built_Assemblies\PreObf\Server\Core\Endpoint\Inspire.Server.ScheduleManager.dll"
Copy "C:\CODE\trunk\InspireServer\Server\Inspire.ServiceHost\bin\Release\Inspire.Server.SlideManager.dll" "C:\CODE\installers\Built_Assemblies\PreObf\Server\Core\Endpoint\Inspire.Server.SlideManager.dll"
Copy "C:\CODE\trunk\InspireServer\Server\Inspire.ServiceHost\bin\Release\Inspire.Server.Users.dll" "C:\CODE\installers\Built_Assemblies\PreObf\Server\Core\Endpoint\Inspire.Server.Users.dll"
Copy "C:\CODE\trunk\InspireServer\Server\Inspire.ServiceHost\bin\Release\Inspire.Server.Settings.dll" "C:\CODE\installers\Built_Assemblies\PreObf\Server\Core\Endpoint\Inspire.Server.Settings.dll"
pause
C:\CODE\installers\Built_Assemblies\babel.exe "C:\CODE\installers\Built_Assemblies\PreObf\Server\Core\Endpoint\Inspire.Server.ServiceHost.exe" --output "C:\CODE\installers\Built_Assemblies\Obfuscated\Server\Core\Endpoint\Inspire.Server.ServiceHost.exe" --noildasm --nomsil --noinvalidopcodes
C:\CODE\installers\Built_Assemblies\babel.exe "C:\CODE\installers\Built_Assemblies\PreObf\Server\Core\Endpoint\Inspire.Server.Common.dll" --output "C:\CODE\installers\Built_Assemblies\Obfuscated\Server\Core\Endpoint\Inspire.Server.Common.dll" --noildasm --nomsil --noinvalidopcodes
C:\CODE\installers\Built_Assemblies\babel.exe "C:\CODE\installers\Built_Assemblies\PreObf\Server\Core\Endpoint\Inspire.Server.Display.dll" --output "C:\CODE\installers\Built_Assemblies\Obfuscated\Server\Core\Endpoint\Inspire.Server.Display.dll" --noildasm --nomsil --noinvalidopcodes
C:\CODE\installers\Built_Assemblies\babel.exe "C:\CODE\installers\Built_Assemblies\PreObf\Server\Core\Endpoint\Inspire.Server.DisplayAdmin.dll" --output "C:\CODE\installers\Built_Assemblies\Obfuscated\Server\Core\Endpoint\Inspire.Server.DisplayAdmin.dll" --noildasm --nomsil --noinvalidopcodes
C:\CODE\installers\Built_Assemblies\babel.exe "C:\CODE\installers\Built_Assemblies\PreObf\Server\Core\Endpoint\Inspire.Server.ScheduledSlideManager.dll" --output "C:\CODE\installers\Built_Assemblies\Obfuscated\Server\Core\Endpoint\Inspire.Server.ScheduledSlideManager.dll" --noildasm --nomsil --noinvalidopcodes
C:\CODE\installers\Built_Assemblies\babel.exe "C:\CODE\installers\Built_Assemblies\PreObf\Server\Core\Endpoint\Inspire.Server.ScheduleManager.dll" --output "C:\CODE\installers\Built_Assemblies\Obfuscated\Server\Core\Endpoint\Inspire.Server.ScheduleManager.dll" --noildasm --nomsil --noinvalidopcodes
C:\CODE\installers\Built_Assemblies\babel.exe "C:\CODE\installers\Built_Assemblies\PreObf\Server\Core\Endpoint\Inspire.Server.SlideManager.dll" --output "C:\CODE\installers\Built_Assemblies\Obfuscated\Server\Core\Endpoint\Inspire.Server.SlideManager.dll" --noildasm --nomsil --noinvalidopcodes
C:\CODE\installers\Built_Assemblies\babel.exe "C:\CODE\installers\Built_Assemblies\PreObf\Server\Core\Endpoint\Inspire.Server.Users.dll" --output "C:\CODE\installers\Built_Assemblies\Obfuscated\Server\Core\Endpoint\Inspire.Server.Users.dll" --noildasm --nomsil --noinvalidopcodes
C:\CODE\installers\Built_Assemblies\babel.exe "C:\CODE\installers\Built_Assemblies\PreObf\Server\Core\Endpoint\Inspire.Server.Settings.dll" --output "C:\CODE\installers\Built_Assemblies\Obfuscated\Server\Core\Endpoint\Inspire.Server.Settings.dll" --noildasm --nomsil --noinvalidopcodes
pause