msbuild C:\CODE\trunk\InspireServer\Events\Inspire.ServiceHost\Inspire.ServiceHost.csproj  /t:Rebuild /p:Configuration=Release /t:Clean

pause

Copy "C:\CODE\trunk\InspireServer\Events\Inspire.ServiceHost\bin\Release\Inspire.Events.ServiceHost.exe" "C:\CODE\installers\Built_Assemblies\PreObf\Server\Events\Endpoint\Inspire.Events.ServiceHost.exe"
Copy "C:\CODE\trunk\InspireServer\Events\Inspire.ServiceHost\bin\Release\Inspire.Server.Common.dll" "C:\CODE\installers\Built_Assemblies\PreObf\Server\Events\Endpoint\Inspire.Server.Common.dll"
Copy "C:\CODE\trunk\InspireServer\Events\Inspire.ServiceHost\bin\Release\Inspire.Server.Common.FaultContracts.dll" "C:\CODE\installers\Built_Assemblies\PreObf\Server\Events\Endpoint\Inspire.Server.Common.FaultContracts.dll"
Copy "C:\CODE\trunk\InspireServer\Events\Inspire.ServiceHost\bin\Release\Inspire.Server.Direction.BusinessLogic.dll" "C:\CODE\installers\Built_Assemblies\PreObf\Server\Events\Endpoint\Inspire.Server.Direction.BusinessLogic.dll"
Copy "C:\CODE\trunk\InspireServer\Events\Inspire.ServiceHost\bin\Release\Inspire.Server.Direction.DataAccess.dll" "C:\CODE\installers\Built_Assemblies\PreObf\Server\Events\Endpoint\Inspire.Server.Direction.DataAccess.dll"
Copy "C:\CODE\trunk\InspireServer\Events\Inspire.ServiceHost\bin\Release\Inspire.Server.Direction.DataContracts.dll" "C:\CODE\installers\Built_Assemblies\PreObf\Server\Events\Endpoint\Inspire.Server.Direction.DataContracts.dll"
Copy "C:\CODE\trunk\InspireServer\Events\Inspire.ServiceHost\bin\Release\Inspire.Server.Direction.MessageContracts.dll" "C:\CODE\installers\Built_Assemblies\PreObf\Server\Events\Endpoint\Inspire.Server.Direction.MessageContracts.dll"
Copy "C:\CODE\trunk\InspireServer\Events\Inspire.ServiceHost\bin\Release\Inspire.Server.Direction.ServiceContracts.dll" "C:\CODE\installers\Built_Assemblies\PreObf\Server\Events\Endpoint\Inspire.Server.Direction.ServiceContracts.dll"
Copy "C:\CODE\trunk\InspireServer\Events\Inspire.ServiceHost\bin\Release\Inspire.Server.Direction.ServiceImplementation.dll" "C:\CODE\installers\Built_Assemblies\PreObf\Server\Events\Endpoint\Inspire.Server.Direction.ServiceImplementation.dll"

Copy "C:\CODE\trunk\InspireServer\Events\Inspire.ServiceHost\bin\Release\Inspire.Server.Events.BusinessLogic.dll" "C:\CODE\installers\Built_Assemblies\PreObf\Server\Events\Endpoint\Inspire.Server.Events.BusinessLogic.dll"
Copy "C:\CODE\trunk\InspireServer\Events\Inspire.ServiceHost\bin\Release\Inspire.Server.Events.DataAccess.dll" "C:\CODE\installers\Built_Assemblies\PreObf\Server\Events\Endpoint\Inspire.Server.Events.DataAccess.dll"
Copy "C:\CODE\trunk\InspireServer\Events\Inspire.ServiceHost\bin\Release\Inspire.Server.Events.DataContracts.dll" "C:\CODE\installers\Built_Assemblies\PreObf\Server\Events\Endpoint\Inspire.Server.Events.DataContracts.dll"
Copy "C:\CODE\trunk\InspireServer\Events\Inspire.ServiceHost\bin\Release\Inspire.Server.Events.MessageContracts.dll" "C:\CODE\installers\Built_Assemblies\PreObf\Server\Events\Endpoint\Inspire.Server.Events.MessageContracts.dll"
Copy "C:\CODE\trunk\InspireServer\Events\Inspire.ServiceHost\bin\Release\Inspire.Server.Events.ServiceContracts.dll" "C:\CODE\installers\Built_Assemblies\PreObf\Server\Events\Endpoint\Inspire.Server.Events.ServiceContracts.dll"
Copy "C:\CODE\trunk\InspireServer\Events\Inspire.ServiceHost\bin\Release\Inspire.Server.Events.ServiceImplementation.ServiceImplementation.dll" "C:\CODE\installers\Built_Assemblies\PreObf\Server\Events\Endpoint\Inspire.Server.Events.ServiceImplementation.ServiceImplementation.dll"

Copy "C:\CODE\trunk\InspireServer\Events\Inspire.ServiceHost\bin\Release\Inspire.Server.Groups.BusinessEntities.dll" "C:\CODE\installers\Built_Assemblies\PreObf\Server\Events\Endpoint\Inspire.Server.Groups.BusinessEntities.dll"
Copy "C:\CODE\trunk\InspireServer\Events\Inspire.ServiceHost\bin\Release\Inspire.Server.Groups.BusinessLogic.dll" "C:\CODE\installers\Built_Assemblies\PreObf\Server\Events\Endpoint\Inspire.Server.Groups.BusinessLogic.dll"
Copy "C:\CODE\trunk\InspireServer\Events\Inspire.ServiceHost\bin\Release\Inspire.Server.Groups.DataAccess.dll" "C:\CODE\installers\Built_Assemblies\PreObf\Server\Events\Endpoint\Inspire.Server.Groups.DataAccess.dll"
Copy "C:\CODE\trunk\InspireServer\Events\Inspire.ServiceHost\bin\Release\Inspire.Server.Groups.DataContracts.dll" "C:\CODE\installers\Built_Assemblies\PreObf\Server\Events\Endpoint\Inspire.Server.Groups.DataContracts.dll"
Copy "C:\CODE\trunk\InspireServer\Events\Inspire.ServiceHost\bin\Release\Inspire.Server.Groups.MessageContracts.dll" "C:\CODE\installers\Built_Assemblies\PreObf\Server\Events\Endpoint\Inspire.Server.Groups.MessageContracts.dll"
Copy "C:\CODE\trunk\InspireServer\Events\Inspire.ServiceHost\bin\Release\Inspire.Server.Groups.ServiceContracts.dll" "C:\CODE\installers\Built_Assemblies\PreObf\Server\Events\Endpoint\Inspire.Server.Groups.ServiceContracts.dll"
Copy "C:\CODE\trunk\InspireServer\Events\Inspire.ServiceHost\bin\Release\Inspire.Server.Groups.ServiceImplementation.dll" "C:\CODE\installers\Built_Assemblies\PreObf\Server\Events\Endpoint\Inspire.Server.Groups.ServiceImplementation.dll"

Copy "C:\CODE\trunk\InspireServer\Events\Inspire.ServiceHost\bin\Release\Inspire.Server.Images.BusinessLogic.dll" "C:\CODE\installers\Built_Assemblies\PreObf\Server\Events\Endpoint\Inspire.Server.Images.BusinessLogic.dll"
Copy "C:\CODE\trunk\InspireServer\Events\Inspire.ServiceHost\bin\Release\Inspire.Server.Images.DataAccess.dll" "C:\CODE\installers\Built_Assemblies\PreObf\Server\Events\Endpoint\Inspire.Server.Images.DataAccess.dll"
Copy "C:\CODE\trunk\InspireServer\Events\Inspire.ServiceHost\bin\Release\Inspire.Server.Images.DataContracts.dll" "C:\CODE\installers\Built_Assemblies\PreObf\Server\Events\Endpoint\Inspire.Server.Images.DataContracts.dll"
Copy "C:\CODE\trunk\InspireServer\Events\Inspire.ServiceHost\bin\Release\Inspire.Server.Images.MessageContracts.dll" "C:\CODE\installers\Built_Assemblies\PreObf\Server\Events\Endpoint\Inspire.Server.Images.MessageContracts.dll"
Copy "C:\CODE\trunk\InspireServer\Events\Inspire.ServiceHost\bin\Release\Inspire.Server.Images.ServiceContracts.dll" "C:\CODE\installers\Built_Assemblies\PreObf\Server\Events\Endpoint\Inspire.Server.Images.ServiceContracts.dll"
Copy "C:\CODE\trunk\InspireServer\Events\Inspire.ServiceHost\bin\Release\Inspire.Server.Images.ServiceImplementation.dll" "C:\CODE\installers\Built_Assemblies\PreObf\Server\Events\Endpoint\Inspire.Server.Images.ServiceImplementation.dll"

Copy "C:\CODE\trunk\InspireServer\Events\Inspire.ServiceHost\bin\Release\Inspire.Server.Rooms.BusinessLogic.dll" "C:\CODE\installers\Built_Assemblies\PreObf\Server\Events\Endpoint\Inspire.Server.Rooms.BusinessLogic.dll"
Copy "C:\CODE\trunk\InspireServer\Events\Inspire.ServiceHost\bin\Release\Inspire.Server.Rooms.DataAccess.dll" "C:\CODE\installers\Built_Assemblies\PreObf\Server\Events\Endpoint\Inspire.Server.Rooms.DataAccess.dll"
Copy "C:\CODE\trunk\InspireServer\Events\Inspire.ServiceHost\bin\Release\Inspire.Server.Rooms.DataContracts.dll" "C:\CODE\installers\Built_Assemblies\PreObf\Server\Events\Endpoint\Inspire.Server.Rooms.DataContracts.dll"
Copy "C:\CODE\trunk\InspireServer\Events\Inspire.ServiceHost\bin\Release\Inspire.Server.Rooms.MessageContracts.dll" "C:\CODE\installers\Built_Assemblies\PreObf\Server\Events\Endpoint\Inspire.Server.Rooms.MessageContracts.dll"
Copy "C:\CODE\trunk\InspireServer\Events\Inspire.ServiceHost\bin\Release\Inspire.Server.Rooms.ServiceContracts.dll" "C:\CODE\installers\Built_Assemblies\PreObf\Server\Events\Endpoint\Inspire.Server.Rooms.ServiceContracts.dll"
Copy "C:\CODE\trunk\InspireServer\Events\Inspire.ServiceHost\bin\Release\Inspire.Server.Rooms.ServiceImplementation.dll" "C:\CODE\installers\Built_Assemblies\PreObf\Server\Events\Endpoint\Inspire.Server.Rooms.ServiceImplementation.dll"

C:\CODE\installers\Built_Assemblies\babel.exe "C:\CODE\installers\Built_Assemblies\PreObf\Server\Events\Endpoint\Inspire.Events.ServiceHost.exe" --output "C:\CODE\installers\Built_Assemblies\Obfuscated\Server\Events\Endpoint\Inspire.Events.ServiceHost.exe" --noildasm --nomsil --noinvalidopcodes
C:\CODE\installers\Built_Assemblies\babel.exe "C:\CODE\installers\Built_Assemblies\PreObf\Server\Events\Endpoint\Inspire.Server.Common.dll" --output "C:\CODE\installers\Built_Assemblies\Obfuscated\Server\Events\Endpoint\Inspire.Server.Common.dll" --noildasm --nomsil --noinvalidopcodes
C:\CODE\installers\Built_Assemblies\babel.exe "C:\CODE\installers\Built_Assemblies\PreObf\Server\Events\Endpoint\Inspire.Server.Common.FaultContracts.dll" --output "C:\CODE\installers\Built_Assemblies\Obfuscated\Server\Events\Endpoint\Inspire.Server.Common.FaultContracts.dll" --noildasm --nomsil --noinvalidopcodes
C:\CODE\installers\Built_Assemblies\babel.exe "C:\CODE\installers\Built_Assemblies\PreObf\Server\Events\Endpoint\Inspire.Server.Direction.BusinessLogic.dll" --output "C:\CODE\installers\Built_Assemblies\Obfuscated\Server\Events\Endpoint\Inspire.Server.Direction.BusinessLogic.dll" --noildasm --nomsil --noinvalidopcodes
C:\CODE\installers\Built_Assemblies\babel.exe "C:\CODE\installers\Built_Assemblies\PreObf\Server\Events\Endpoint\Inspire.Server.Direction.DataAccess.dll" --output "C:\CODE\installers\Built_Assemblies\Obfuscated\Server\Events\Endpoint\Inspire.Server.Direction.DataAccess.dll" --noildasm --nomsil --noinvalidopcodes
C:\CODE\installers\Built_Assemblies\babel.exe "C:\CODE\installers\Built_Assemblies\PreObf\Server\Events\Endpoint\Inspire.Server.Direction.DataContracts.dll" --output "C:\CODE\installers\Built_Assemblies\Obfuscated\Server\Events\Endpoint\Inspire.Server.Direction.DataContracts.dll" --noildasm --nomsil --noinvalidopcodes
C:\CODE\installers\Built_Assemblies\babel.exe "C:\CODE\installers\Built_Assemblies\PreObf\Server\Events\Endpoint\Inspire.Server.Direction.MessageContracts.dll" --output "C:\CODE\installers\Built_Assemblies\Obfuscated\Server\Events\Endpoint\Inspire.Server.Direction.MessageContracts.dll" --noildasm --nomsil --noinvalidopcodes
C:\CODE\installers\Built_Assemblies\babel.exe "C:\CODE\installers\Built_Assemblies\PreObf\Server\Events\Endpoint\Inspire.Server.Direction.ServiceContracts.dll" --output "C:\CODE\installers\Built_Assemblies\Obfuscated\Server\Events\Endpoint\Inspire.Server.Direction.ServiceContracts.dll" --noildasm --nomsil --noinvalidopcodes
C:\CODE\installers\Built_Assemblies\babel.exe "C:\CODE\installers\Built_Assemblies\PreObf\Server\Events\Endpoint\Inspire.Server.Direction.ServiceImplementation.dll" --output "C:\CODE\installers\Built_Assemblies\Obfuscated\Server\Events\Endpoint\Inspire.Server.Direction.ServiceImplementation.dll" --noildasm --nomsil --noinvalidopcodes
"
C:\CODE\installers\Built_Assemblies\babel.exe "C:\CODE\installers\Built_Assemblies\PreObf\Server\Events\Endpoint\Inspire.Server.Events.BusinessLogic.dll" --output "C:\CODE\installers\Built_Assemblies\Obfuscated\Server\Events\Endpoint\Inspire.Server.Events.BusinessLogic.dll" --noildasm --nomsil --noinvalidopcodes
C:\CODE\installers\Built_Assemblies\babel.exe "C:\CODE\installers\Built_Assemblies\PreObf\Server\Events\Endpoint\Inspire.Server.Events.DataAccess.dll" --output "C:\CODE\installers\Built_Assemblies\Obfuscated\Server\Events\Endpoint\Inspire.Server.Events.DataAccess.dll" --noildasm --nomsil --noinvalidopcodes
C:\CODE\installers\Built_Assemblies\babel.exe "C:\CODE\installers\Built_Assemblies\PreObf\Server\Events\Endpoint\Inspire.Server.Events.DataContracts.dll" --output "C:\CODE\installers\Built_Assemblies\Obfuscated\Server\Events\Endpoint\Inspire.Server.Events.DataContracts.dll" --noildasm --nomsil --noinvalidopcodes
C:\CODE\installers\Built_Assemblies\babel.exe "C:\CODE\installers\Built_Assemblies\PreObf\Server\Events\Endpoint\Inspire.Server.Events.MessageContracts.dll" --output "C:\CODE\installers\Built_Assemblies\Obfuscated\Server\Events\Endpoint\Inspire.Server.Events.MessageContracts.dll" --noildasm --nomsil --noinvalidopcodes
C:\CODE\installers\Built_Assemblies\babel.exe "C:\CODE\installers\Built_Assemblies\PreObf\Server\Events\Endpoint\Inspire.Server.Events.ServiceContracts.dll" --output "C:\CODE\installers\Built_Assemblies\Obfuscated\Server\Events\Endpoint\Inspire.Server.Events.ServiceContracts.dll" --noildasm --nomsil --noinvalidopcodes
C:\CODE\installers\Built_Assemblies\babel.exe "C:\CODE\installers\Built_Assemblies\PreObf\Server\Events\Endpoint\Inspire.Server.Events.ServiceImplementation.ServiceImplementation.dll" --output "C:\CODE\installers\Built_Assemblies\Obfuscated\Server\Events\Endpoint\Inspire.Server.Events.ServiceImplementation.ServiceImplementation.dll" --noildasm --nomsil --noinvalidopcodes

C:\CODE\installers\Built_Assemblies\babel.exe "C:\CODE\installers\Built_Assemblies\PreObf\Server\Events\Endpoint\Inspire.Server.Groups.BusinessEntities.dll" --output "C:\CODE\installers\Built_Assemblies\Obfuscated\Server\Events\Endpoint\Inspire.Server.Groups.BusinessEntities.dll" --noildasm --nomsil --noinvalidopcodes
C:\CODE\installers\Built_Assemblies\babel.exe "C:\CODE\installers\Built_Assemblies\PreObf\Server\Events\Endpoint\Inspire.Server.Groups.BusinessLogic.dll" --output "C:\CODE\installers\Built_Assemblies\Obfuscated\Server\Events\Endpoint\Inspire.Server.Groups.BusinessLogic.dll" --noildasm --nomsil --noinvalidopcodes
C:\CODE\installers\Built_Assemblies\babel.exe "C:\CODE\installers\Built_Assemblies\PreObf\Server\Events\Endpoint\Inspire.Server.Groups.DataAccess.dll" --output "C:\CODE\installers\Built_Assemblies\Obfuscated\Server\Events\Endpoint\Inspire.Server.Groups.DataAccess.dll" --noildasm --nomsil --noinvalidopcodes
C:\CODE\installers\Built_Assemblies\babel.exe "C:\CODE\installers\Built_Assemblies\PreObf\Server\Events\Endpoint\Inspire.Server.Groups.DataContracts.dll" --output "C:\CODE\installers\Built_Assemblies\Obfuscated\Server\Events\Endpoint\Inspire.Server.Groups.DataContracts.dll" --noildasm --nomsil --noinvalidopcodes
C:\CODE\installers\Built_Assemblies\babel.exe "C:\CODE\installers\Built_Assemblies\PreObf\Server\Events\Endpoint\Inspire.Server.Groups.MessageContracts.dll" --output "C:\CODE\installers\Built_Assemblies\Obfuscated\Server\Events\Endpoint\Inspire.Server.Groups.MessageContracts.dll" --noildasm --nomsil --noinvalidopcodes
C:\CODE\installers\Built_Assemblies\babel.exe "C:\CODE\installers\Built_Assemblies\PreObf\Server\Events\Endpoint\Inspire.Server.Groups.ServiceContracts.dll" --output "C:\CODE\installers\Built_Assemblies\Obfuscated\Server\Events\Endpoint\Inspire.Server.Groups.ServiceContracts.dll" --noildasm --nomsil --noinvalidopcodes
C:\CODE\installers\Built_Assemblies\babel.exe "C:\CODE\installers\Built_Assemblies\PreObf\Server\Events\Endpoint\Inspire.Server.Groups.ServiceImplementation.dll" --output "C:\CODE\installers\Built_Assemblies\Obfuscated\Server\Events\Endpoint\Inspire.Server.Groups.ServiceImplementation.dll" --noildasm --nomsil --noinvalidopcodes

C:\CODE\installers\Built_Assemblies\babel.exe "C:\CODE\installers\Built_Assemblies\PreObf\Server\Events\Endpoint\Inspire.Server.Images.BusinessLogic.dll" --output "C:\CODE\installers\Built_Assemblies\Obfuscated\Server\Events\Endpoint\Inspire.Server.Images.BusinessLogic.dll" --noildasm --nomsil --noinvalidopcodes
C:\CODE\installers\Built_Assemblies\babel.exe "C:\CODE\installers\Built_Assemblies\PreObf\Server\Events\Endpoint\Inspire.Server.Images.DataAccess.dll" --output "C:\CODE\installers\Built_Assemblies\Obfuscated\Server\Events\Endpoint\Inspire.Server.Images.DataAccess.dll" --noildasm --nomsil --noinvalidopcodes
C:\CODE\installers\Built_Assemblies\babel.exe "C:\CODE\installers\Built_Assemblies\PreObf\Server\Events\Endpoint\Inspire.Server.Images.DataContracts.dll" --output "C:\CODE\installers\Built_Assemblies\Obfuscated\Server\Events\Endpoint\Inspire.Server.Images.DataContracts.dll" --noildasm --nomsil --noinvalidopcodes
C:\CODE\installers\Built_Assemblies\babel.exe "C:\CODE\installers\Built_Assemblies\PreObf\Server\Events\Endpoint\Inspire.Server.Images.MessageContracts.dll" --output "C:\CODE\installers\Built_Assemblies\Obfuscated\Server\Events\Endpoint\Inspire.Server.Images.MessageContracts.dll" --noildasm --nomsil --noinvalidopcodes
C:\CODE\installers\Built_Assemblies\babel.exe "C:\CODE\installers\Built_Assemblies\PreObf\Server\Events\Endpoint\Inspire.Server.Images.ServiceContracts.dll" --output "C:\CODE\installers\Built_Assemblies\Obfuscated\Server\Events\Endpoint\Inspire.Server.Images.ServiceContracts.dll" --noildasm --nomsil --noinvalidopcodes
C:\CODE\installers\Built_Assemblies\babel.exe "C:\CODE\installers\Built_Assemblies\PreObf\Server\Events\Endpoint\Inspire.Server.Images.ServiceImplementation.dll" --output "C:\CODE\installers\Built_Assemblies\Obfuscated\Server\Events\Endpoint\Inspire.Server.Images.ServiceImplementation.dll" --noildasm --nomsil --noinvalidopcodes

C:\CODE\installers\Built_Assemblies\babel.exe "C:\CODE\installers\Built_Assemblies\PreObf\Server\Events\Endpoint\Inspire.Server.Rooms.BusinessLogic.dll" --output "C:\CODE\installers\Built_Assemblies\Obfuscated\Server\Events\Endpoint\Inspire.Server.Rooms.BusinessLogic.dll" --noildasm --nomsil --noinvalidopcodes
C:\CODE\installers\Built_Assemblies\babel.exe "C:\CODE\installers\Built_Assemblies\PreObf\Server\Events\Endpoint\Inspire.Server.Rooms.DataAccess.dll" --output "C:\CODE\installers\Built_Assemblies\Obfuscated\Server\Events\Endpoint\Inspire.Server.Rooms.DataAccess.dll" --noildasm --nomsil --noinvalidopcodes
C:\CODE\installers\Built_Assemblies\babel.exe "C:\CODE\installers\Built_Assemblies\PreObf\Server\Events\Endpoint\Inspire.Server.Rooms.DataContracts.dll" --output "C:\CODE\installers\Built_Assemblies\Obfuscated\Server\Events\Endpoint\Inspire.Server.Rooms.DataContracts.dll" --noildasm --nomsil --noinvalidopcodes
C:\CODE\installers\Built_Assemblies\babel.exe "C:\CODE\installers\Built_Assemblies\PreObf\Server\Events\Endpoint\Inspire.Server.Rooms.MessageContracts.dll" --output "C:\CODE\installers\Built_Assemblies\Obfuscated\Server\Events\Endpoint\Inspire.Server.Rooms.MessageContracts.dll" --noildasm --nomsil --noinvalidopcodes
C:\CODE\installers\Built_Assemblies\babel.exe "C:\CODE\installers\Built_Assemblies\PreObf\Server\Events\Endpoint\Inspire.Server.Rooms.ServiceContracts.dll" --output "C:\CODE\installers\Built_Assemblies\Obfuscated\Server\Events\Endpoint\Inspire.Server.Rooms.ServiceContracts.dll" --noildasm --nomsil --noinvalidopcodes
C:\CODE\installers\Built_Assemblies\babel.exe "C:\CODE\installers\Built_Assemblies\PreObf\Server\Events\Endpoint\Inspire.Server.Rooms.ServiceImplementation.dll" --output "C:\CODE\installers\Built_Assemblies\Obfuscated\Server\Events\Endpoint\Inspire.Server.Rooms.ServiceImplementation.dll" --noildasm --nomsil --noinvalidopcodes
