//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;


namespace Inspire.Display.Service.XML
{
    /// <summary>
    /// Data Contract Class - Button 
    /// </summary>
  
    public partial class Button
    {       
        public string GUID { get; set; }       
        public string SlideID { get; set; }        
        public string ButtonName { get; set; }
        public string ScheduledSlidSlideID { get; set; }
        public string SlideGuidToNavigateTo { get; set; }
        
    }       
}

