//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Inspire.Display.Service.XML
{
	/// <summary>
	/// Data Contract Class - ScheduleSlides
	/// </summary>
	public partial class ScheduleSlides : System.Collections.Generic.List<ScheduleSlide>
	{
	}
}

